WebApiProject_CE004/CourseAllocationCoreClient/CourseAllocationCoreClient/Models/Faculty.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CourseAllocationCoreClient.Models
{
    public class Faculty
    {
        [Required]
        [EmailAddress]
        public string Username { get; set; }

        [Required]
        public int? Experience { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        public string Password { get; set; }
    }
}

WebApiProject_CE004/CourseAllocationCoreClient/CourseAllocationCoreClient/Controllers/FacultyController.cs
using CourseAllocationCoreClient.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace CourseAllocationCoreClient.Controllers
{
    public class FacultyController : Controller
    {
        public IActionResult Index()
        {
            IEnumerable<Faculty> faculties = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44336/api/");
                var resultTask = client.GetAsync("faculty");
                resultTask.Wait();
                var result = resultTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Faculty>>();
                    readTask.Wait();
                    faculties = readTask.Result;
                }
                else
                {
                    faculties = Enumerable.Empty<Faculty>();
                    ModelState.AddModelError(string.Empty, "server Error.Please contact admin");
                }
            }
            return View(faculties);
           
        }

        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Create(Faculty faculty)
        {
            string name = faculty.FirstName;
            faculty.Password = name + "@2000";
            if (ModelState.IsValid)
            {

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44336/api/faculty");
                    var post = client.PostAsJsonAsync<Faculty>("faculty", faculty);
                    post.Wait();
                    var result = post.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }

                }
            }

            return View();
        }

        public IActionResult Delete(string id)
        {
            ViewBag.Id = id;
            
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44336/api/");
                var deleteTask = client.DeleteAsync("faculty?username="+id);

                var result = deleteTask.Result;
                if(result.IsSuccessStatusCode)
                {       
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.status = result.ReasonPhrase+ " "+result.Content;
                }
            }
            return View("Delete");
        }
    }
}

WebApiProject_CE004/CourseAllocationCoreClient/CourseAllocationCoreClient/Controllers/LoginController.cs
using CourseAllocationCoreClient.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace CourseAllocationCoreClient.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(Login login)
        {
           
            if (ModelState.IsValid)
            {
                if(login.Username.Equals("pankajjalote@gmail.com") && login.Password.Equals("admin123"))
                {
                    return View("AdminHomepage");
                }
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44336/api/login");
                    var post = client.PostAsJsonAsync<Login>("login", login);
                    post.Wait();
                    var result = post.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return View("Homepage",login);
                    }

                }
            }
            return View();
        }

        public IActionResult ViewAllocation(string username)
        {
            ViewBag.Name = username;
            IEnumerable<Allocation> allocations1 = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44336/api/");
                var resultTask = client.GetAsync("allocation");
                resultTask.Wait();
                var result = resultTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Allocation>>();
                    readTask.Wait();
                    allocations1 = readTask.Result;
                }
            }
            return View("ShowAllocation",allocations1);
        }

        public IActionResult AdminHome()
        {
            return View("AdminHomepage");
        }
    }

  

}

WebApiProject_CE004/CourseAllocationCoreClient/CourseAllocationCoreClient/Views/Faculty/Create.cshtml
@model CourseAllocationCoreClient.Models.Faculty

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Faculty</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Add Faculty" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApiProject_CE004/CourseAllocationCoreClient/CourseAllocationCoreClient/Views/Faculty/Delete.cshtml
<h1>Faculty Deletion Unsuccessful for Faculty with id:@ViewBag.Id with status code @ViewBag.status</h1>

<br /><br />

<a asp-action="Index" asp-controller="Faculty" class="btn btn-info"> Go to Faculties Homepage </a>

WebApiProject_CE004/CourseAllocationCoreClient/CourseAllocationCoreClient/Views/Faculty/Index.cshtml
@model IEnumerable<CourseAllocationCoreClient.Models.Faculty>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Experience)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Experience)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
               
                @Html.ActionLink("Delete", "Delete", new { id=item.Username })
            </td>
        </tr>
}
    </tbody>
</table>

WebApiProject_CE004/CourseAllocationCoreClient/CourseAllocationCoreClient/Views/Faculty/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseAllocationCoreClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Course Allocation System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="AdminHome">Homepage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CourseAllocationCoreClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>